<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="F_SYSTEM_TimeFine" Id="{a3f67e31-403f-4012-b8f4-dc88ecbad23b}" SpecialFunc="None">
    <Declaration><![CDATA[(* generate time as HHMMSST from TIMESTRUCT value *)
FUNCTION F_SYSTEM_TimeFine : STRING(7)
VAR_INPUT
	sTime		: TIMESTRUCT;
END_VAR
VAR
END_VAR
(*
-------------------------------------------------------------------------------------------------
Date		Version	Author	Comments
-------------------------------------------------------------------------------------------------
03/08/2012	1.39.00	PB		Initial release

-------------------------------------------------------------------------------------------------
*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_SYSTEM_TimeFine := F_CONCAT4(F_ZeroPadString(WORD_TO_STRING(sTime.wHour), 2),
								F_ZeroPadString(WORD_TO_STRING(sTime.wMinute), 2),
								F_ZeroPadString(WORD_TO_STRING(sTime.wSecond), 2),
								F_ZeroPadString(WORD_TO_STRING(sTime.wMilliseconds / 100), 1));]]></ST>
    </Implementation>
    <LineIds Name="F_SYSTEM_TimeFine">
      <LineId Id="16" Count="3" />
    </LineIds>
  </POU>
</TcPlcObject>