<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="F_SYSTEM_Date" Id="{8d10908f-3ec7-4cf6-81ad-453913460491}" SpecialFunc="None">
    <Declaration><![CDATA[(* generate date as YYYYMMDD from TIMESTRUCT value *)
FUNCTION F_SYSTEM_Date : STRING(8)
VAR_INPUT
	sTime		: TIMESTRUCT;
END_VAR
VAR
END_VAR
(*
-------------------------------------------------------------------------------------------------
Date		Version	Author	Comments
-------------------------------------------------------------------------------------------------
03/08/2012	1.39.00	PB		Initial release

-------------------------------------------------------------------------------------------------
*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_SYSTEM_Date := F_CONCAT3(F_ZeroPadString(WORD_TO_STRING(sTime.wYear), 4),
							F_ZeroPadString(WORD_TO_STRING(sTime.wMonth), 2),
							F_ZeroPadString(WORD_TO_STRING(sTime.wDay), 2));]]></ST>
    </Implementation>
    <LineIds Name="F_SYSTEM_Date">
      <LineId Id="16" Count="2" />
    </LineIds>
  </POU>
</TcPlcObject>