<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="F_SYSTEM_HMIDateTime_V2" Id="{13f86f04-8f53-42f9-9c08-86282e3370ca}" SpecialFunc="None">
    <Declaration><![CDATA[(* generate date/time as HH:MM:SS DD/MM/YYYY from TIMESTRUCT value *)
FUNCTION F_SYSTEM_HMIDateTime_V2 : STRING(19)
VAR_INPUT
	sTime		: TIMESTRUCT;
END_VAR
VAR
END_VAR
(*
-------------------------------------------------------------------------------------------------
Date		Version	Author	Comments
-------------------------------------------------------------------------------------------------
03/08/2012	1.39.00	PB		Initial release

-------------------------------------------------------------------------------------------------
*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_SYSTEM_HMIDateTime_V2 := F_CONCAT6(	F_ZeroPadString(WORD_TO_STRING(sTime.wHour), 2), ':',
									F_ZeroPadString(WORD_TO_STRING(sTime.wMinute), 2), ':',
									F_ZeroPadString(WORD_TO_STRING(sTime.wSecond), 2), ' ');

F_SYSTEM_HMIDateTime_V2 := F_CONCAT6(	F_SYSTEM_HMIDateTime_V2,
									F_ZeroPadString(WORD_TO_STRING(sTime.wDay), 2), '/',
									F_ZeroPadString(WORD_TO_STRING(sTime.wMonth), 2), '/',
									F_ZeroPadString(WORD_TO_STRING(sTime.wYear), 4));]]></ST>
    </Implementation>
    <LineIds Name="F_SYSTEM_HMIDateTime_V2">
      <LineId Id="16" Count="7" />
    </LineIds>
  </POU>
</TcPlcObject>