<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_CASE_ValidateContentTests" Id="{822c9689-f495-489e-84c7-63cbf678b11e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CASE_ValidateContentTests EXTENDS TcUnit.FB_TestSuite

VAR
	
(* General data *)
	stCTDateTime_tests					: ST_SYSTEM_DateTime;	
	stProductInstruction_tests			: ST_PCM_Status;
	nSecquentionalCounter_tests			: UDINT;
	stCodeInfo_Outer_tests				: ST_CodeInfo;
	stCaseRejectReasons_tests			: ST_RejectReasonsForCase;
	stRejectReasonsForOuter_tests		: ST_RejectReasonsForOuter;
	stOuterDataNotFound_tests			: ST_RejectItems;

(* 01.Main tests container *)

	stProductInstruction_test_0101		: ST_PCM_Status;
	stCACData_test_0101 				: ST_CAC_Data;
		
	stCACData_tests 					: ST_CAC_Data;
(* 02.DataConsistancy tests container *)
	stProductInstruction_test_0201		: ST_PCM_Status;
	stCACData_test_0201 				: ST_CAC_Data;
	sRejectCode_test_0201				: T_MaxString;
	
	stProductInstruction_test_0202		: ST_PCM_Status;
	stCACData_test_0202 				: ST_CAC_Data;
	sRejectCode_test_0202				: T_MaxString;	
	
	
	stProductInstruction_test_0203		: ST_PCM_Status;
	stCACData_test_0203 				: ST_CAC_Data;
	sRejectCode_test_0203				: T_MaxString;
	
	stProductInstruction_test_0204		: ST_PCM_Status;
	stCACData_test_0204 				: ST_CAC_Data;
	sRejectCode_test_0204				: T_MaxString;

	
	stProductInstruction_test_0205		: ST_PCM_Status;
	stCACData_test_0205 				: ST_CAC_Data;
	sRejectCode_test_0205				: T_MaxString;
	
	stProductInstruction_test_0206		: ST_PCM_Status;
	stCACData_test_0206 				: ST_CAC_Data;
	sRejectCode_test_0206				: T_MaxString;

(* 03.NumberOfOuters tests container *)
	stProductInstruction_test_0301		: ST_PCM_Status;
	stCACData_test_0301 				: ST_CAC_Data;
	sRejectCode_test_0301				: T_MaxString;
	
	stProductInstruction_test_0302		: ST_PCM_Status;
	stCACData_test_0302 				: ST_CAC_Data;
	sRejectCode_test_0302				: T_MaxString;
	
	stProductInstruction_test_0303		: ST_PCM_Status;
	stCACData_test_0303 				: ST_CAC_Data;
	sRejectCode_test_0303				: T_MaxString;
	
(* 04.OuterAggrDissable tests container *)
	stProductInstruction_test_0401		: ST_PCM_Status;
	stCACData_test_0401 				: ST_CAC_Data;
	sRejectCode_test_0401				: T_MaxString;
	
	stProductInstruction_test_0402		: ST_PCM_Status;
	stCACData_test_0402 				: ST_CAC_Data;
	sRejectCode_test_0402				: T_MaxString;

(* 05.OuterAggrEnable tests container *)
	stProductInstruction_test_0501		: ST_PCM_Status;
	stCACData_test_0501 				: ST_CAC_Data;
	sRejectCode_test_0501				: T_MaxString;
	
	stProductInstruction_test_0502		: ST_PCM_Status;
	stCACData_test_0502 				: ST_CAC_Data;
	sRejectCode_test_0502				: T_MaxString;

(* 06.DuplicateHandler tests container *)
	
	stProductInstruction_test_0601		: ST_PCM_Status;
	stCACData_test_0601 				: ST_CAC_Data;
	sRejectCode_test_0601				: T_MaxString;
	
	stCACData_test_0602 				: ST_CAC_Data;
	stProductInstruction_test_0602		: ST_PCM_Status;
	sRejectCode_test_0602				: T_MaxString;
	
(* 07.OACmissing tests container *)
	
	stProductInstruction_test_0701		: ST_PCM_Status;
	stCACData_test_0701 				: ST_CAC_Data;
	sRejectCode_test_0701				: T_MaxString;
	
	stCACData_test_0702 				: ST_CAC_Data;
	stProductInstruction_test_0702		: ST_PCM_Status;
	sRejectCode_test_0702				: T_MaxString;
	
	sRejectCode_tets					: T_MaxString;
	
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[
//==============================================================
//01.Main
//==============================================================
main01_bExecuteFalseNoAction();
//==============================================================
//02.DataConsistancy
//==============================================================
dataConsistancy01_NumOfOutersWrong();
dataConsistancy02_NumOfOutersExceedcMAX_Outers();
dataConsistancy03_ValidationCodeNotFoundInInfeedQueue();
dataConsistancy04_OuterCodeVal_IndexErrorFound();
dataConsistancy05_NumberOfOutersToSmall();
dataConsistancy06_NumberOfOutersToBig();

//==============================================================
//03.NumberOfOuters
//==============================================================
numberOfOuters01_ValueToLittlebErrorTrue();
numberOfOuters02_ValueGraterErrorTrue();
numberOfOuters03_ValueToLittlebErrorTrueRejectCodeWright();

//==============================================================
//04.OuterAggrDissable
//==============================================================
outerAggrDissable01_sRejectCodeOK();

//==============================================================
//05.OuterAggrEnable
//==============================================================
outerAggrEnable01_PacksPerOuterZero();
outerAggrEnable02_PacksPerCaseZero();


//==============================================================
//06.DuplicatesHandler
//==============================================================
duplicateHandler01_OuterDuplicatebErrorTrue();
duplicateHandler02_PackDuplicatebErrorTrue();

//==============================================================
//07.OACmissing
//==============================================================
oacMissing01nErrorID21();]]></ST>
    </Implementation>
    <Folder Name="01.Main" Id="{3efa2ee4-d7cd-44eb-a85a-a0e477b57b3b}" />
    <Folder Name="02.DataConsistancy" Id="{693924a5-42e2-4208-b929-e9e914d01e79}" />
    <Folder Name="03.NumberOfOuters" Id="{b0fe4446-7114-4527-b271-a6e33e4ed61f}" />
    <Folder Name="04.OuterAggrDissable" Id="{8114e77b-5754-4ae2-91e5-6dedce0f4fa5}" />
    <Folder Name="05.OuterAggrEnable" Id="{cbcc7ee9-3d0b-492a-abb0-b08e73444fc1}" />
    <Folder Name="06. DuplicatesHandler" Id="{2a79a149-c2ae-4192-80f2-d9269d1098d2}" />
    <Folder Name="07.OACmissing" Id="{c48d55b4-192e-4e54-9884-7295a025f741}" />
    <Method Name="dataConsistancy01_NumOfOutersWrong" Id="{5a7eb3c1-3834-4161-b3a1-4b3b49744cac}" FolderPath="02.DataConsistancy\">
      <Declaration><![CDATA[METHOD INTERNAL dataConsistancy01_NumOfOutersWrong
VAR
	//fbCaseTest			: FB_CASE_ValidateContent;
	bDone				: BOOL;
	bBusy				: BOOL;
	bError				: BOOL;
	nErrorID 			: UDINT;
	nValidationIndex	: INT;
	
	eLastState			: E_CAC_State;
			
END_VAR

VAR_INST
	fbCaseTest0201				: FB_CASE_ValidateContent;
	rTrig0201					: R_TRIG;
	nCycles0201					: INT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//Data initialization
TestInit(stCACData:= stCACData_test_0201, stProductInstruction:= stProductInstruction_test_0201);

//Change some data for test scenario below
stCACData_test_0201.NumberOfOuters := stCACData_test_0201.NumberOfOuters - 2;
	
TcUnit.TEST('dataConsistancy01_NumOfOutersWrong');


fbCaseTest0201(
	bExecute:= TRUE, 
	bIsDuplicateOuters:= FALSE, 
	bIsDuplicatePacks:= FALSE, 
	stCTDateTime:= stCTDateTime_tests, 
	stOuterDataNotFound:= stRejectReasonsForOuter_tests.stOuterDataNotFound, 
	stProductInstruction:= stProductInstruction_test_0201, 
	nSecquentionalCounter:= nSecquentionalCounter_tests, 
	stCodeInfo_Outer:= stCodeInfo_Outer_tests, 
	stCaseRejectReasons:= stCaseRejectReasons_tests, 
	stCACData:= stCACData_test_0201, 
	bDone=> bDone, 
	bBusy=> bBusy, 
	bError=> bError, 
	nErrorID=> nErrorID, 
	sRejectCode=> sRejectCode_test_0201, 
	nValidationIndex=> nValidationIndex
);
	
rTrig0201(CLK:= fbCaseTest0201.bDone);
nCycles0201 := nCycles0201 + 1;	

IF rTrig0201.Q THEN	
		
	AssertEquals_BOOL(Expected 	:= TRUE,
					  Actual 	:= bError,
					  Message 	:= 'Wrong number of outers not detected'
	);
	
	AssertEquals_STRING(Expected := 'XXVAL048XX',
						Actual := TO_STRING(fbCaseTest0201.sRejectCode),
						Message := 'Wrong value of nErrorID'
	);
	
	TEST_FINISHED();
	
ELSIF nCycles0201 > 50 THEN
	
	AssertTrue(Condition := TRUE,
			   Message 	 := 'Timeout dataConsistancy01_NumOfOutersWrong'
	);	 
	TEST_FINISHED();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="dataConsistancy02_NumOfOutersExceedcMAX_Outers" Id="{44487056-36e5-48a9-a070-4cc0b8ddab89}" FolderPath="02.DataConsistancy\">
      <Declaration><![CDATA[METHOD INTERNAL dataConsistancy02_NumOfOutersExceedcMAX_Outers
VAR
	//fbCaseTest			: FB_CASE_ValidateContent;
	bDone				: BOOL;
	bBusy				: BOOL;
	bError				: BOOL;
	nErrorID 			: UDINT;
	nValidationIndex	: INT;
	
	eLastState			: E_CAC_State;
			
END_VAR

VAR_INST
	fbCaseTest0202				: FB_CASE_ValidateContent;
	rTrig0202					: R_TRIG;
	nCycles0202					: INT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//Data initialization
TestInit(stCACData:= stCACData_test_0202, stProductInstruction:= stProductInstruction_test_0202);

//Change some data for test scenario below
stCACData_test_0202.NumberOfOuters := - 1;
	
TcUnit.TEST('dataConsistancy02_NumOfOutersExceedcMAX_Outers');


fbCaseTest0202(
	bExecute:= TRUE, 
	bIsDuplicateOuters:= FALSE, 
	bIsDuplicatePacks:= FALSE, 
	stCTDateTime:= stCTDateTime_tests, 
	stOuterDataNotFound:= stRejectReasonsForOuter_tests.stOuterDataNotFound, 
	stProductInstruction:= stProductInstruction_test_0202, 
	nSecquentionalCounter:= nSecquentionalCounter_tests, 
	stCodeInfo_Outer:= stCodeInfo_Outer_tests, 
	stCaseRejectReasons:= stCaseRejectReasons_tests, 
	stCACData:= stCACData_test_0202, 
	bDone=> bDone, 
	bBusy=> bBusy, 
	bError=> bError, 
	nErrorID=> nErrorID, 
	sRejectCode=> sRejectCode_test_0202, 
	nValidationIndex=> nValidationIndex
);
	
rTrig0202(CLK:= fbCaseTest0202.bDone);
nCycles0202 := nCycles0202 + 1;	

IF rTrig0202.Q THEN	
		
	AssertEquals_UDINT(Expected := 11,
                   	   Actual 	:= fbCaseTest0202.nErrorID,
                   	   Message 	:= 'nErrorID value wrong');
	
	TEST_FINISHED();
	
ELSIF nCycles0202 > 50 THEN
	
	AssertTrue(Condition := TRUE,
			   Message 	 := 'Timeout dataConsistancy02_NumOfOutersExceedcMAX_Outers'
	);	 
	TEST_FINISHED();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="dataConsistancy03_ValidationCodeNotFoundInInfeedQueue" Id="{336ee4a9-f0b9-4995-a14e-1e9387bc4d30}" FolderPath="02.DataConsistancy\">
      <Declaration><![CDATA[METHOD INTERNAL dataConsistancy03_ValidationCodeNotFoundInInfeedQueue
VAR
	//fbCaseTest			: FB_CASE_ValidateContent;
	bDone				: BOOL;
	bBusy				: BOOL;
	bError				: BOOL;
	nErrorID 			: UDINT;
	nValidationIndex	: INT;
	
	eLastState			: E_CAC_State;
			
END_VAR

VAR_INST
	fbCaseTest0203				: FB_CASE_ValidateContent;
	rTrig0203					: R_TRIG;
	nCycles0203					: INT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//Data initialization
TestInit(stCACData:= stCACData_test_0203, stProductInstruction:= stProductInstruction_test_0203);

//Change some data for test scenario below
stCACData_test_0203.NumberOfOuters := - 2;
	
TcUnit.TEST('dataConsistancy03_ValidationCodeNotFoundInInfeedQueue');


fbCaseTest0203(
	bExecute:= TRUE, 
	bIsDuplicateOuters:= FALSE, 
	bIsDuplicatePacks:= FALSE, 
	stCTDateTime:= stCTDateTime_tests, 
	stOuterDataNotFound:= stRejectReasonsForOuter_tests.stOuterDataNotFound, 
	stProductInstruction:= stProductInstruction_test_0203, 
	nSecquentionalCounter:= nSecquentionalCounter_tests, 
	stCodeInfo_Outer:= stCodeInfo_Outer_tests, 
	stCaseRejectReasons:= stCaseRejectReasons_tests, 
	stCACData:= stCACData_test_0203, 
	bDone=> bDone, 
	bBusy=> bBusy, 
	bError=> bError, 
	nErrorID=> nErrorID, 
	sRejectCode=> sRejectCode_test_0203, 
	nValidationIndex=> nValidationIndex
);
	
rTrig0203(CLK:= fbCaseTest0203.bDone);
nCycles0203 := nCycles0203 + 1;	

IF rTrig0203.Q THEN	
		
	AssertEquals_UDINT(Expected := 12,
                   	   Actual 	:= fbCaseTest0203.nErrorID,
                   	   Message 	:= 'nErrorID value wrong');
	
	TEST_FINISHED();
	
ELSIF nCycles0203 > 50 THEN
	
	AssertTrue(Condition := TRUE,
			   Message 	 := 'Timeout dataConsistancy03_ValidationCodeNotFoundInInfeedQueue'
	);	 
	TEST_FINISHED();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="dataConsistancy04_OuterCodeVal_IndexErrorFound" Id="{686d66b9-d06b-4802-9001-b193a66c464a}" FolderPath="02.DataConsistancy\">
      <Declaration><![CDATA[METHOD INTERNAL dataConsistancy04_OuterCodeVal_IndexErrorFound
VAR
	//fbCaseTest			: FB_CASE_ValidateContent;
	bDone				: BOOL;
	bBusy				: BOOL;
	bError				: BOOL;
	nErrorID 			: UDINT;
	nValidationIndex	: INT;
	
	eLastState			: E_CAC_State;
			
END_VAR

VAR_INST
	fbCaseTest0204				: FB_CASE_ValidateContent;
	rTrig0204					: R_TRIG;
	nCycles0204					: INT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//Data initialization
TestInit(stCACData:= stCACData_test_0204, stProductInstruction:= stProductInstruction_test_0204);

//Change some data for test scenario below
stCACData_test_0204.NumberOfOuters := - 3;
	
TcUnit.TEST('dataConsistancy04_OuterCodeVal_IndexErrorFound');


fbCaseTest0204(
	bExecute:= TRUE, 
	bIsDuplicateOuters:= FALSE, 
	bIsDuplicatePacks:= FALSE, 
	stCTDateTime:= stCTDateTime_tests, 
	stOuterDataNotFound:= stRejectReasonsForOuter_tests.stOuterDataNotFound, 
	stProductInstruction:= stProductInstruction_test_0204, 
	nSecquentionalCounter:= nSecquentionalCounter_tests, 
	stCodeInfo_Outer:= stCodeInfo_Outer_tests, 
	stCaseRejectReasons:= stCaseRejectReasons_tests, 
	stCACData:= stCACData_test_0204, 
	bDone=> bDone, 
	bBusy=> bBusy, 
	bError=> bError, 
	nErrorID=> nErrorID, 
	sRejectCode=> sRejectCode_test_0204, 
	nValidationIndex=> nValidationIndex
);
	
rTrig0204(CLK:= fbCaseTest0204.bDone);
nCycles0204 := nCycles0204 + 1;	

IF rTrig0204.Q THEN	
		
	AssertEquals_UDINT(Expected := 13,
                   	   Actual 	:= fbCaseTest0204.nErrorID,
                   	   Message 	:= 'nErrorID value wrong');
	
	TEST_FINISHED();
	
ELSIF nCycles0204 > 50 THEN
	
	AssertTrue(Condition := TRUE,
			   Message 	 := 'Timeout dataConsistancy04_OuterCodeVal_IndexErrorFound'
	);	 
	TEST_FINISHED();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="dataConsistancy05_NumberOfOutersToSmall" Id="{baa97d41-ea49-4e2b-b29e-f927dec1b38f}" FolderPath="02.DataConsistancy\">
      <Declaration><![CDATA[METHOD INTERNAL dataConsistancy05_NumberOfOutersToSmall
VAR
	//fbCaseTest			: FB_CASE_ValidateContent;
	bDone				: BOOL;
	bBusy				: BOOL;
	bError				: BOOL;
	nErrorID 			: UDINT;
	nValidationIndex	: INT;
	
	eLastState			: E_CAC_State;
			
END_VAR

VAR_INST
	fbCaseTest0205				: FB_CASE_ValidateContent;
	rTrig0205					: R_TRIG;
	nCycles0205					: INT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//Data initialization
TestInit(stCACData:= stCACData_test_0205, stProductInstruction:= stProductInstruction_test_0205);

//Change some data for test scenario below
stCACData_test_0205.NumberOfOuters := 25;
	
TcUnit.TEST('dataConsistancy05_NumberOfOutersToSmall');


fbCaseTest0205(
	bExecute:= TRUE, 
	bIsDuplicateOuters:= FALSE, 
	bIsDuplicatePacks:= FALSE, 
	stCTDateTime:= stCTDateTime_tests, 
	stOuterDataNotFound:= stRejectReasonsForOuter_tests.stOuterDataNotFound, 
	stProductInstruction:= stProductInstruction_test_0205, 
	nSecquentionalCounter:= nSecquentionalCounter_tests, 
	stCodeInfo_Outer:= stCodeInfo_Outer_tests, 
	stCaseRejectReasons:= stCaseRejectReasons_tests, 
	stCACData:= stCACData_test_0205, 
	bDone=> bDone, 
	bBusy=> bBusy, 
	bError=> bError, 
	nErrorID=> nErrorID, 
	sRejectCode=> sRejectCode_test_0205, 
	nValidationIndex=> nValidationIndex
);
	
rTrig0205(CLK:= fbCaseTest0205.bDone);
nCycles0205 := nCycles0205 + 1;	

IF rTrig0205.Q THEN	
		
	AssertEquals_UDINT(Expected := 14,
                   	   Actual 	:= fbCaseTest0205.nErrorID,
                   	   Message 	:= 'nErrorID value wrong');
	
	TEST_FINISHED();
	
ELSIF nCycles0205 > 50 THEN
	
	AssertTrue(Condition := TRUE,
			   Message 	 := 'Timeout dataConsistancy05_NumberOfOutersToSmall'
	);	 
	TEST_FINISHED();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="dataConsistancy06_NumberOfOutersToBig" Id="{ed90598c-8ff8-4e58-92d2-64c6196f1963}" FolderPath="02.DataConsistancy\">
      <Declaration><![CDATA[METHOD INTERNAL dataConsistancy06_NumberOfOutersToBig
VAR
	//fbCaseTest			: FB_CASE_ValidateContent;
	bDone				: BOOL;
	bBusy				: BOOL;
	bError				: BOOL;
	nErrorID 			: UDINT;
	nValidationIndex	: INT;
	
	eLastState			: E_CAC_State;
			
END_VAR

VAR_INST
	fbCaseTest0206				: FB_CASE_ValidateContent;
	rTrig0206					: R_TRIG;
	nCycles0206					: INT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//Data initialization
TestInit(stCACData:= stCACData_test_0206, stProductInstruction:= stProductInstruction_test_0206);

//Change some data for test scenario below
stCACData_test_0206.NumberOfOuters := 69;
	
TcUnit.TEST('dataConsistancy06_NumberOfOutersToBig');


fbCaseTest0206(
	bExecute:= TRUE, 
	bIsDuplicateOuters:= FALSE, 
	bIsDuplicatePacks:= FALSE, 
	stCTDateTime:= stCTDateTime_tests, 
	stOuterDataNotFound:= stRejectReasonsForOuter_tests.stOuterDataNotFound, 
	stProductInstruction:= stProductInstruction_test_0206, 
	nSecquentionalCounter:= nSecquentionalCounter_tests, 
	stCodeInfo_Outer:= stCodeInfo_Outer_tests, 
	stCaseRejectReasons:= stCaseRejectReasons_tests, 
	stCACData:= stCACData_test_0206, 
	bDone=> bDone, 
	bBusy=> bBusy, 
	bError=> bError, 
	nErrorID=> nErrorID, 
	sRejectCode=> sRejectCode_test_0206, 
	nValidationIndex=> nValidationIndex
);
	
rTrig0206(CLK:= fbCaseTest0206.bDone);
nCycles0206 := nCycles0206 + 1;	

IF rTrig0206.Q THEN	
		
	AssertEquals_UDINT(Expected := 15,
                   	   Actual 	:= fbCaseTest0206.nErrorID,
                   	   Message 	:= 'nErrorID value wrong');
	
	TEST_FINISHED();
	
ELSIF nCycles0206 > 50 THEN
	
	AssertTrue(Condition := TRUE,
			   Message 	 := 'Timeout dataConsistancy06_NumberOfOutersToBig'
	);	 
	TEST_FINISHED();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="duplicateHandler01_OuterDuplicatebErrorTrue" Id="{78319de4-45f3-4e2b-a121-b631d955473f}" FolderPath="06. DuplicatesHandler\">
      <Declaration><![CDATA[METHOD INTERNAL duplicateHandler01_OuterDuplicatebErrorTrue
VAR
	//fbCaseTest			: FB_CASE_ValidateContent;
	bDone				: BOOL;
	bBusy				: BOOL;
	bError				: BOOL;
	nErrorID 			: UDINT;
	nValidationIndex	: INT;
	
	eLastState			: E_CAC_State;
			
END_VAR

VAR_INST
	fbCaseTest0601				: FB_CASE_ValidateContent;
	fTrig						: F_TRIG;	
	rTrig						: R_TRIG;
	nCycles						: INT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//Data initialization
TestInit(stCACData:= stCACData_test_0601, stProductInstruction:= stProductInstruction_test_0601);

//Change some data for test scenario below
//stCACData_test_0303.NumberOfOuters := 51;

	
TcUnit.TEST('duplicateHandler01_OuterDuplicatebErrorTrue');



fbCaseTest0601(
	bExecute:= TRUE, 
	bIsDuplicateOuters:= TRUE, 
	bIsDuplicatePacks:= FALSE, 
	stCTDateTime:= stCTDateTime_tests, 
	stOuterDataNotFound:= stRejectReasonsForOuter_tests.stOuterDataNotFound, 
	stProductInstruction:= stProductInstruction_test_0601, 
	nSecquentionalCounter:= nSecquentionalCounter_tests, 
	stCodeInfo_Outer:= stCodeInfo_Outer_tests, 
	stCaseRejectReasons:= stCaseRejectReasons_tests, 
	stCACData:= stCACData_test_0601, 
	bDone=> bDone, 
	bBusy=> bBusy, 
	bError=> bError, 
	nErrorID=> nErrorID, 
	sRejectCode=> sRejectCode_tets, 
	nValidationIndex=> nValidationIndex
);
	
rTrig(CLK:= fbCaseTest0601.bDone);
nCycles := nCycles + 1;	

IF rTrig.Q THEN	
		
	AssertEquals_BOOL(Expected 	:= TRUE,
					  Actual 	:= bError,
					  Message 	:= 'Outer duplicate did not call error'
	);
	
	AssertEquals_UDINT(Expected := 1,
                   	   Actual 	:= fbCaseTest0601.nErrorID,
                   	   Message 	:= 'Wrong nErrorID on outer duplicate'
	);
	
	TEST_FINISHED();
	
ELSIF nCycles > 50 THEN
	
	AssertTrue(Condition := TRUE,
			   Message 	 := 'Timeout duplicateHandler01_OuterDuplicatebErrorTrue'
	);	 
	TEST_FINISHED();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="duplicateHandler02_PackDuplicatebErrorTrue" Id="{464dcacd-701b-41b2-9a7f-ba9a23d3d004}" FolderPath="06. DuplicatesHandler\">
      <Declaration><![CDATA[METHOD INTERNAL duplicateHandler02_PackDuplicatebErrorTrue
VAR
	//fbCaseTest			: FB_CASE_ValidateContent;
	bDone				: BOOL;
	bBusy				: BOOL;
	bError				: BOOL;
	nErrorID 			: UDINT;
	nValidationIndex	: INT;
	
	eLastState			: E_CAC_State;
			
END_VAR

VAR_INST
	fbCaseTest0602				: FB_CASE_ValidateContent;
	fTrig						: F_TRIG;	
	rTrig						: R_TRIG;
	nCycles						: INT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//Data initialization
TestInit(stCACData:= stCACData_test_0602, stProductInstruction:= stProductInstruction_test_0602);

//Change some data for test scenario below

	
TcUnit.TEST('duplicateHandler02_PackDuplicatebErrorTrue');


fbCaseTest0602(
	bExecute:= TRUE, 
	bIsDuplicateOuters:= FALSE, 
	bIsDuplicatePacks:= TRUE, 
	stCTDateTime:= stCTDateTime_tests, 
	stOuterDataNotFound:= stRejectReasonsForOuter_tests.stOuterDataNotFound, 
	stProductInstruction:= stProductInstruction_test_0602, 
	nSecquentionalCounter:= nSecquentionalCounter_tests, 
	stCodeInfo_Outer:= stCodeInfo_Outer_tests, 
	stCaseRejectReasons:= stCaseRejectReasons_tests, 
	stCACData:= stCACData_test_0602, 
	bDone=> bDone, 
	bBusy=> bBusy, 
	bError=> bError, 
	nErrorID=> nErrorID, 
	sRejectCode=> sRejectCode_tets, 
	nValidationIndex=> nValidationIndex
);
	
rTrig(CLK:= fbCaseTest0602.bDone);
nCycles := nCycles + 1;	

IF rTrig.Q THEN	
		
	AssertEquals_BOOL(Expected 	:= TRUE,
					  Actual 	:= bError,
					  Message 	:= 'Pack duplicate did not call error'
	);
	
	AssertEquals_UDINT(Expected := 1,
                   	   Actual 	:= fbCaseTest0602.nErrorID,
                   	   Message 	:= 'Wrong nErrorID on pack duplicate'
	);
	
	TEST_FINISHED();
	
ELSIF nCycles > 50 THEN
	
	AssertTrue(Condition := TRUE,
			   Message 	 := 'Timeout duplicateHandler02_PackDuplicatebErrorTrue'
	);	 
	TEST_FINISHED();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="main01_bExecuteFalseNoAction" Id="{329929f8-6ef8-4f4c-8fb5-705facb92eaf}" FolderPath="01.Main\">
      <Declaration><![CDATA[METHOD INTERNAL main01_bExecuteFalseNoAction
VAR
	//fbCaseTest			: FB_CASE_ValidateContent;
	bDone				: BOOL;
	bBusy				: BOOL;
	bError				: BOOL;
	nErrorID 			: UDINT;
	nValidationIndex	: INT;
	
	eLastState			: E_CAC_State;
			
END_VAR

VAR_INST
	fbCaseTest0101				: FB_CASE_ValidateContent;
	fTrig						: F_TRIG;	
	rTrig						: R_TRIG;
	nCycles						: INT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//Data initialization
TestInit(stCACData:= stCACData_test_0101, stProductInstruction:= stProductInstruction_test_0101);

//Change some data for test scenario below

	
TcUnit.TEST('main01_bExecuteFalseNoAction');


fbCaseTest0101(
	bExecute:= FALSE, 
	bIsDuplicateOuters:= FALSE, 
	bIsDuplicatePacks:= FALSE, 
	stCTDateTime:= stCTDateTime_tests, 
	stOuterDataNotFound:= stRejectReasonsForOuter_tests.stOuterDataNotFound, 
	stProductInstruction:= stProductInstruction_test_0101, 
	nSecquentionalCounter:= nSecquentionalCounter_tests, 
	stCodeInfo_Outer:= stCodeInfo_Outer_tests, 
	stCaseRejectReasons:= stCaseRejectReasons_tests, 
	stCACData:= stCACData_test_0101, 
	bDone=> bDone, 
	bBusy=> bBusy, 
	bError=> bError, 
	nErrorID=> nErrorID, 
	sRejectCode=> sRejectCode_tets, 
	nValidationIndex=> nValidationIndex
);
	
rTrig(CLK:= fbCaseTest0101.bDone);
nCycles := nCycles + 1;	

		
AssertEquals_BOOL(Expected 	:= FALSE,
				  Actual 	:= fbCaseTest0101.bError,
				  Message 	:= 'FB no executed wrong output'
);

AssertEquals_BOOL(Expected 	:= FALSE,
				  Actual 	:= fbCaseTest0101.bDone,
				  Message 	:= 'B no executed wrong output'
);

TEST_FINISHED();]]></ST>
      </Implementation>
    </Method>
    <Method Name="numberOfOuters01_ValueToLittlebErrorTrue" Id="{b44f659f-6262-4429-8424-4805520f7114}" FolderPath="03.NumberOfOuters\">
      <Declaration><![CDATA[METHOD INTERNAL numberOfOuters01_ValueToLittlebErrorTrue
VAR
	//fbCaseTest			: FB_CASE_ValidateContent;
	bDone				: BOOL;
	bBusy				: BOOL;
	bError				: BOOL;
	nErrorID 			: UDINT;
	nValidationIndex	: INT;
	
	eLastState			: E_CAC_State;
			
END_VAR

VAR_INST
	fbCaseTest0301				: FB_CASE_ValidateContent;
	fTrig0301						: F_TRIG;
	nCycles0301						: INT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//Data initialization
TestInit(stCACData:= stCACData_test_0301, stProductInstruction:= stProductInstruction_test_0301);

//Change some data for test scenario below
stCACData_test_0301.NumberOfOuters := 45;
	


TcUnit.TEST('numberOfOuters01_ValueToLittlebErrorTrue');

fbCaseTest0301(
	bExecute:= TRUE, 
	bIsDuplicateOuters:= FALSE, 
	bIsDuplicatePacks:= FALSE, 
	stCTDateTime:= stCTDateTime_tests, 
	stOuterDataNotFound:= stRejectReasonsForOuter_tests.stOuterDataNotFound, 
	stProductInstruction:= stProductInstruction_test_0301, 
	nSecquentionalCounter:= nSecquentionalCounter_tests, 
	stCodeInfo_Outer:= stCodeInfo_Outer_tests, 
	stCaseRejectReasons:= stCaseRejectReasons_tests, 
	stCACData:= stCACData_test_0301, 
	bDone=> bDone, 
	bBusy=> bBusy, 
	bError=> bError, 
	nErrorID=> nErrorID, 
	sRejectCode=> sRejectCode_test_0301, 
	nValidationIndex=> nValidationIndex
);

fTrig0301(CLK:= fbCaseTest0301.bBusy);
nCycles0301 := nCycles0301 + 1;	

IF fTrig0301.Q AND nCycles0301 <= 50 THEN	
	
	AssertEquals_BOOL(Expected := TRUE,
					  Actual := fbCaseTest0301.bError,
					  Message := 'Numbers of outer wrong value didnt call error'
	);
	
	AssertEquals_STRING(Expected := 'XXVAL045XX',
						Actual := TO_STRING(fbCaseTest0301.sRejectCode),
						Message := 'Wrong value of nErrorID'
	);
	
	AssertEquals_INT(Expected := 45,
					 Actual := stCACData_test_0301.NumberOfOuters,
					 Message := 'INT Values differ'
	);	
	
	TEST_FINISHED();
	
ELSIF nCycles0301 > 50 THEN
	
	AssertTrue(Condition := TRUE,
			   Message := 'Timeout CASE loop within FB_CASE_Validation'
	);	 

	
	TEST_FINISHED();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="numberOfOuters02_ValueGraterErrorTrue" Id="{c972d737-2a90-4c98-9612-4a477f5a6a2a}" FolderPath="03.NumberOfOuters\">
      <Declaration><![CDATA[METHOD INTERNAL numberOfOuters02_ValueGraterErrorTrue
VAR
	
	bDone				: BOOL;
	bBusy				: BOOL;
	bError				: BOOL;
	nErrorID 			: UDINT;
	nValidationIndex	: INT;
	
	eLastState			: E_CAC_State;
	
		
END_VAR

VAR_INST
	
	fbCaseTest0302				: FB_CASE_ValidateContent;
	fTrig0302						: F_TRIG;
	nCycles0302						: INT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//Data initialization
TestInit(stCACData:= stCACData_test_0302, stProductInstruction:= stProductInstruction_test_0302);

//Change some data for test scenario below
stCACData_test_0302.NumberOfOuters := 79;

	
TcUnit.TEST('numberOfOuters02_ValueGraterErrorTrue');


fbCaseTest0302(
	bExecute:= TRUE, 
	bIsDuplicateOuters:= FALSE, 
	bIsDuplicatePacks:= FALSE, 
	stCTDateTime:= stCTDateTime_tests, 
	stOuterDataNotFound:= stRejectReasonsForOuter_tests.stOuterDataNotFound, 
	stProductInstruction:= stProductInstruction_test_0302, 
	nSecquentionalCounter:= nSecquentionalCounter_tests, 
	stCodeInfo_Outer:= stCodeInfo_Outer_tests, 
	stCaseRejectReasons:= stCaseRejectReasons_tests, 
	stCACData:= stCACData_test_0302, 
	bDone=> bDone, 
	bBusy=> bBusy, 
	bError=> bError, 
	nErrorID=> nErrorID, 
	sRejectCode=> sRejectCode_test_0302, 
	nValidationIndex=> nValidationIndex
);
	
fTrig0302(CLK:= fbCaseTest0302.bBusy);
nCycles0302 := nCycles0302 + 1;	

IF fTrig0302.Q AND nCycles0302 <= 50 THEN	
		
	AssertEquals_BOOL(Expected := TRUE,
					  Actual := fbCaseTest0302.bError,
					  Message := 'Numbers of outer wrong value didnt call error'
	);
	
	AssertEquals_STRING(Expected := 'XXVAL079XX',
						Actual := TO_STRING(fbCaseTest0302.sRejectCode),
						Message := 'Wrong value of sRejectCode'
	);
	
	TEST_FINISHED();
	
ELSIF nCycles0302 > 50 THEN
	
	AssertTrue(Condition := TRUE,
			   Message 	 := 'Timeout numberOfOuters02_ValueGraterErrorTrue'
	);	 
	
	TEST_FINISHED();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="numberOfOuters03_ValueToLittlebErrorTrueRejectCodeWright" Id="{bd5ef02a-e2be-4a30-99c6-36465cea1130}" FolderPath="03.NumberOfOuters\">
      <Declaration><![CDATA[METHOD INTERNAL numberOfOuters03_ValueToLittlebErrorTrueRejectCodeWright
VAR
	//fbCaseTest			: FB_CASE_ValidateContent;
	bDone				: BOOL;
	bBusy				: BOOL;
	bError				: BOOL;
	nErrorID 			: UDINT;
	nValidationIndex	: INT;
	
	eLastState			: E_CAC_State;
			
END_VAR

VAR_INST
	fbCaseTest0303				: FB_CASE_ValidateContent;
	fTrig						: F_TRIG;
	nCycles						: INT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//Data initialization
TestInit(stCACData:= stCACData_test_0303, stProductInstruction:= stProductInstruction_test_0303);

//Change some data for test scenario below
stCACData_test_0303.NumberOfOuters := 51;

	
TcUnit.TEST('numberOfOuters03_ValueToLittlebErrorTrueRejectCodeWright');


fbCaseTest0303(
	bExecute:= TRUE, 
	bIsDuplicateOuters:= FALSE, 
	bIsDuplicatePacks:= FALSE, 
	stCTDateTime:= stCTDateTime_tests, 
	stOuterDataNotFound:= stRejectReasonsForOuter_tests.stOuterDataNotFound, 
	stProductInstruction:= stProductInstruction_test_0301, 
	nSecquentionalCounter:= nSecquentionalCounter_tests, 
	stCodeInfo_Outer:= stCodeInfo_Outer_tests, 
	stCaseRejectReasons:= stCaseRejectReasons_tests, 
	stCACData:= stCACData_test_0303, 
	bDone=> bDone, 
	bBusy=> bBusy, 
	bError=> bError, 
	nErrorID=> nErrorID, 
	sRejectCode=> sRejectCode_test_0303, 
	nValidationIndex=> nValidationIndex
);
	
fTrig(CLK:= fbCaseTest0303.bBusy);
nCycles := nCycles + 1;	

IF fTrig.Q THEN	
		
	AssertEquals_BOOL(Expected := TRUE,
					  Actual := fbCaseTest0303.bError,
					  Message := 'Numbers of outer wrong value didnt call error'
	);
	
	AssertEquals_STRING(Expected := 'XXVAL051XX',
						Actual := TO_STRING(fbCaseTest0303.sRejectCode),
						Message := 'Wrong value of sRejectCode'
	);
	
	TEST_FINISHED();
	
ELSIF nCycles > 50 THEN
	
	AssertTrue(Condition := TRUE,
			   Message 	 := 'Timeout numberOfOuters03_ValueToLittlebErrorTrueRejectCodeWright'
	);	 
	
	TEST_FINISHED();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="oacMissing01nErrorID21" Id="{4db39697-f6a8-4ae3-8b98-60380f7630eb}" FolderPath="07.OACmissing\">
      <Declaration><![CDATA[METHOD INTERNAL oacMissing01nErrorID21
VAR
	//fbCaseTest			: FB_CASE_ValidateContent;
	bDone				: BOOL;
	bBusy				: BOOL;
	bError				: BOOL;
	nErrorID 			: UDINT;
	nValidationIndex	: INT;
	bCompare			: BOOL;
	
	eLastState			: E_CAC_State;
			
END_VAR

VAR_INST
	fbCaseTest0701				: FB_CASE_ValidateContent;
	fTrig0701					: F_TRIG;	
	rTrig0701					: R_TRIG;
	nCycles0701					: INT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//Data initialization
TestInit(stCACData:= stCACData_test_0701, stProductInstruction:= stProductInstruction_test_0701);

//Change some data for test scenario below
stCACData_test_0701.Outer[5].OuterRejectID := 207;
stProductInstruction_test_0701.nCaseAcceptanceLevelOuters := 60;
stProductInstruction_test_0701.nOuterAcceptanceLevelPacks := 100;
stProductInstruction_test_0701.nCaseAcceptanceLevelPacks  := 100;
	
TcUnit.TEST('oacMissing01nErrorID21');


fbCaseTest0701(
	bExecute:= TRUE, 
	bIsDuplicateOuters:= FALSE, 
	bIsDuplicatePacks:= FALSE, 
	stCTDateTime:= stCTDateTime_tests, 
	stOuterDataNotFound:= stRejectReasonsForOuter_tests.stOuterDataNotFound, 
	stProductInstruction:= stProductInstruction_test_0701, 
	nSecquentionalCounter:= nSecquentionalCounter_tests, 
	stCodeInfo_Outer:= stCodeInfo_Outer_tests, 
	stCaseRejectReasons:= stCaseRejectReasons_tests, 
	stCACData:= stCACData_test_0701, 
	bDone=> bDone, 
	bBusy=> bBusy, 
	bError=> bError, 
	nErrorID=> nErrorID, 
	sRejectCode=> sRejectCode_tets, 
	nValidationIndex=> nValidationIndex
);
	
rTrig0701(CLK:= fbCaseTest0701.bDone);
nCycles0701 := nCycles0701 + 1;	



IF rTrig0701.Q THEN	
	
	bCompare := (stCACData_test_0701.CaseRejectID = stCaseRejectReasons_tests.stOACError.nRejectID);
	
	AssertEquals_BOOL(Expected 	:= TRUE,
					  Actual 	:= bError,
					  Message 	:= 'Pack duplicate did not call error'
	);
	
	AssertEquals_UDINT(Expected := 21,
                   	   Actual 	:= fbCaseTest0701.nErrorID,
                   	   Message 	:= 'Wrong nErrorID on OAC missing'
	);
	
	AssertEquals_BOOL(Expected 	:= TRUE,
					  Actual 	:= bCompare,
					  Message 	:= 'CaseRejectID wrong value'
	);	
	
	TEST_FINISHED();
	
ELSIF nCycles0701 > 50 THEN
	
	AssertTrue(Condition := FALSE,
			   Message 	 := 'Timeout oacMissing01nErrorID21'
	);	 
	TEST_FINISHED();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="outerAggrDissable01_sRejectCodeOK" Id="{b06415b8-82f7-4342-9ca6-63537f192528}" FolderPath="04.OuterAggrDissable\">
      <Declaration><![CDATA[METHOD INTERNAL outerAggrDissable01_sRejectCodeOK
VAR
	//fbCaseTest			: FB_CASE_ValidateContent;
	bDone				: BOOL;
	bBusy				: BOOL;
	bError				: BOOL;
	nErrorID 			: UDINT;
	nValidationIndex	: INT;
	
	eLastState			: E_CAC_State;
			
END_VAR

VAR_INST
	fbCaseTest0401				: FB_CASE_ValidateContent;
	rTrig0401					: R_TRIG;
	nCycles0401					: INT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//Data initialization
TestInit(stCACData:= stCACData_test_0401, stProductInstruction:= stProductInstruction_test_0401);

//Change some data for test scenario below
stCACData_test_0401.CodingAndTrackingMode := 6;
	
TcUnit.TEST('outerAggrDissable01_sRejectCodeOK');


fbCaseTest0401(
	bExecute:= TRUE, 
	bIsDuplicateOuters:= FALSE, 
	bIsDuplicatePacks:= FALSE, 
	stCTDateTime:= stCTDateTime_tests, 
	stOuterDataNotFound:= stOuterDataNotFound_tests, 
	stProductInstruction:= stProductInstruction_test_0401, 
	nSecquentionalCounter:= nSecquentionalCounter_tests, 
	stCodeInfo_Outer:= stCodeInfo_Outer_tests, 
	stCaseRejectReasons:= stCaseRejectReasons_tests, 
	stCACData:= stCACData_test_0401, 
	bDone=> bDone, 
	bBusy=> bBusy, 
	bError=> bError, 
	nErrorID=> nErrorID, 
	sRejectCode=> sRejectCode_test_0401, 
	nValidationIndex=> nValidationIndex
);
	
rTrig0401(CLK:= fbCaseTest0401.bDone);
nCycles0401 := nCycles0401 + 1;	

IF rTrig0401.Q THEN	
	
	AssertEquals_STRING(Expected := 'OK',
						Actual := TO_STRING(fbCaseTest0401.sRejectCode),
						Message := 'Wrong value of nErrorID'
	);
	
	
	TEST_FINISHED();
	
ELSIF nCycles0401 > 50 THEN
	
	AssertTrue(Condition := TRUE,
			   Message 	 := 'Timeout outerAggrDissable01_sRejectCodeOK'
	);	 
	TEST_FINISHED();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="outerAggrEnable01_PacksPerOuterZero" Id="{f6354401-6d2d-4be3-8465-0b6cab005959}" FolderPath="05.OuterAggrEnable\">
      <Declaration><![CDATA[METHOD INTERNAL outerAggrEnable01_PacksPerOuterZero
VAR
	//fbCaseTest			: FB_CASE_ValidateContent;
	bDone				: BOOL;
	bBusy				: BOOL;
	bError				: BOOL;
	nErrorID 			: UDINT;
	nValidationIndex	: INT;
	
	eLastState			: E_CAC_State;
			
END_VAR

VAR_INST
	fbCaseTest0501				: FB_CASE_ValidateContent;
	rTrig0501					: R_TRIG;
	nCycles0501					: INT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//Data initialization
TestInit(stCACData:= stCACData_test_0501, stProductInstruction:= stProductInstruction_test_0501);

//Change some data for test scenario below
stCACData_test_0501.CodingAndTrackingMode := 8;
stProductInstruction_test_0501.nPacksPerOuter := 0;
	
TcUnit.TEST('outerAggrEnable01_PacksPerOuterZero');


fbCaseTest0501(
	bExecute:= TRUE, 
	bIsDuplicateOuters:= FALSE, 
	bIsDuplicatePacks:= FALSE, 
	stCTDateTime:= stCTDateTime_tests, 
	stOuterDataNotFound:= stRejectReasonsForOuter_tests.stOuterDataNotFound, 
	stProductInstruction:= stProductInstruction_test_0501, 
	nSecquentionalCounter:= nSecquentionalCounter_tests, 
	stCodeInfo_Outer:= stCodeInfo_Outer_tests, 
	stCaseRejectReasons:= stCaseRejectReasons_tests, 
	stCACData:= stCACData_test_0501, 
	bDone=> bDone, 
	bBusy=> bBusy, 
	bError=> bError, 
	nErrorID=> nErrorID, 
	sRejectCode=> sRejectCode_test_0501, 
	nValidationIndex=> nValidationIndex
);
	
rTrig0501(CLK:= fbCaseTest0501.bDone);
nCycles0501 := nCycles0501 + 1;	

IF rTrig0501.Q THEN	
	
	AssertEquals_BOOL(Expected 	:= TRUE,
					  Actual 	:= bError,
					  Message 	:= 'Wrong number of outers not detected'
	);

	AssertEquals_UDINT(Expected := 10,
                   	   Actual 	:= fbCaseTest0501.nErrorID,
                   	   Message 	:= 'nErrorID value wrong'
	);
	
	
	TEST_FINISHED();
	
ELSIF nCycles0501 > 50 THEN
	
	AssertTrue(Condition := TRUE,
			   Message 	 := 'Timeout outerAggrEnable01_PacksPerOuterZero'
	);	 
	TEST_FINISHED();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="outerAggrEnable02_PacksPerCaseZero" Id="{0d9a9e76-b6f3-4c6f-8d77-0ee26456190c}" FolderPath="05.OuterAggrEnable\">
      <Declaration><![CDATA[METHOD INTERNAL outerAggrEnable02_PacksPerCaseZero
VAR
	//fbCaseTest			: FB_CASE_ValidateContent;
	bDone				: BOOL;
	bBusy				: BOOL;
	bError				: BOOL;
	nErrorID 			: UDINT;
	nValidationIndex	: INT;
	
	eLastState			: E_CAC_State;
			
END_VAR

VAR_INST
	fbCaseTest0502				: FB_CASE_ValidateContent;
	rTrig0502					: R_TRIG;
	nCycles0502					: INT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//Data initialization
TestInit(stCACData:= stCACData_test_0502, stProductInstruction:= stProductInstruction_test_0502);

//Change some data for test scenario below
stCACData_test_0502.CodingAndTrackingMode := 8;
stProductInstruction_test_0502.nPacksPerCase := 0;
	
TcUnit.TEST('outerAggrEnable02_PacksPerCaseZero');


fbCaseTest0502(
	bExecute:= TRUE, 
	bIsDuplicateOuters:= FALSE, 
	bIsDuplicatePacks:= FALSE, 
	stCTDateTime:= stCTDateTime_tests, 
	stOuterDataNotFound:= stRejectReasonsForOuter_tests.stOuterDataNotFound, 
	stProductInstruction:= stProductInstruction_test_0502, 
	nSecquentionalCounter:= nSecquentionalCounter_tests, 
	stCodeInfo_Outer:= stCodeInfo_Outer_tests, 
	stCaseRejectReasons:= stCaseRejectReasons_tests, 
	stCACData:= stCACData_test_0502, 
	bDone=> bDone, 
	bBusy=> bBusy, 
	bError=> bError, 
	nErrorID=> nErrorID, 
	sRejectCode=> sRejectCode_test_0502, 
	nValidationIndex=> nValidationIndex
);
	
rTrig0502(CLK:= fbCaseTest0502.bDone);
nCycles0502 := nCycles0502 + 1;	

IF rTrig0502.Q THEN	
	
	AssertEquals_BOOL(Expected 	:= TRUE,
					  Actual 	:= bError,
					  Message 	:= 'Wrong number of outers not detected'
	);

	AssertEquals_UDINT(Expected := 10,
                   	   Actual 	:= fbCaseTest0502.nErrorID,
                   	   Message 	:= 'nErrorID value wrong'
	);
	
	
	TEST_FINISHED();
	
ELSIF nCycles0502 > 50 THEN
	
	AssertTrue(Condition := TRUE,
			   Message 	 := 'Timeout outerAggrEnable02_PacksPerCaseZero'
	);	 
	TEST_FINISHED();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="TestInit" Id="{e5298ae0-bc3f-4459-8b9d-7da53c4ceb10}">
      <Declaration><![CDATA[METHOD PRIVATE TestInit : BOOL
VAR_IN_OUT
	stProductInstruction	: ST_PCM_Status;
	stCACData 				: ST_CAC_Data;
END_VAR

VAR	
	rTrigDataInit		: R_TRIG;
	bDataInit			: BOOL;
	iOuter				: INT;
	iPack				: INT;
	sPackNum			: STRING;
	sOuterNum			: STRING;
	sPackCode			: STRING;
END_VAR

VAR_OUTPUT
	bDone				: BOOL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[
//MEMSET(ADR(stCACData), 16#00, SIZEOF(stCACData));	

stProductInstruction.nOutersPerCase 	:= 50;
stProductInstruction.nPacksPerOuter		:= 10;
stProductInstruction.nPacksPerCase		:= 500;
stProductInstruction.nOpMode			:= 11;
stProductInstruction.sRetailSKU			:= '1234567';
stProductInstruction.nAcceptanceLevel 	:= 10;

stCACData.NumberOfOuters			:= stProductInstruction.nOutersPerCase;
stCACData.CodingAndTrackingMode		:= stProductInstruction.nOpMode;
stCACData.RetailSKU					:= stProductInstruction.sRetailSKU;

FOR iOuter := 1 TO stProductInstruction.nOutersPerCase DO
	(* Outer number z zerami *)
	sOuterNum := F_StringAddPrefix(INT_TO_STRING(iOuter),2,'0');

	stCACData.Outer[iOuter].Barcode    				:= CONCAT('OUTER', sOuterNum);
	stCACData.Outer[iOuter].NumberOfPacks 			:= stProductInstruction.nPacksPerOuter;
	stCACData.Outer[iOuter].NumberOfLinkedPacks 	:= stProductInstruction.nPacksPerOuter;
	stCACData.Outer[iOuter].AcceptanceLevel 		:= stProductInstruction.nAcceptanceLevel;
	stCACData.Outer[iOuter].CodingAndTrackingMode	:= stProductInstruction.nOpMode;
	stCACData.Outer[iOuter].OuterRejectCode			:= 'OK';

	FOR iPack := 1 TO stProductInstruction.nPacksPerOuter DO
		(* Pack number dwucyfrowy z zerami *)
		sPackNum := F_StringAddPrefix(INT_TO_STRING(iPack),2,'0');			
		(* Sklej pack code *)
		sPackCode := CONCAT(CONCAT('PACK', sPackNum), CONCAT('OUTER', sOuterNum));
		
		(* Write Pack Barcodes / Data*)
		stCACData.Outer[iOuter].PackCode[iPack]				:= sPackCode;
		stCACData.Outer[iOuter].PackCodeStatus[iPack]		:= 5;
		stCACData.Outer[iOuter].PackRejectID[iPack]			:= 0;			
		stCACData.Outer[iOuter].PackRejectCode[iPack]		:= 'OK';			
		stCACData.Outer[iOuter].PackCodeStatus[iPack].5 	:= TRUE;
		
		
		IF iPack = 1 THEN
			stCACData.Outer[iOuter].AggregationCodes[1]	:= stCACData.Outer[iOuter].PackCode[iPack];
		END_IF
		IF iPack = 2 THEN
			stCACData.Outer[iOuter].AggregationCodes[2]	:= stCACData.Outer[iOuter].PackCode[iPack];
		END_IF
	END_FOR
END_FOR	

stCACData.Outer[3].OuterCodeStatus.5 	:= TRUE;
stCACData.Outer[4].OuterCodeStatus.5	:= TRUE;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>