<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="F_FILE_FileTimeToULarge" Id="{eb9ddf76-162b-454f-bce8-d456beb5cbae}" SpecialFunc="None">
    <Declaration><![CDATA[(* convert value from 64-bit T_FILETIME to 64-bit T_ULARGE_INTEGER *)
FUNCTION F_FILE_FileTimeToULarge : T_ULARGE_INTEGER
VAR_INPUT
	sFileTime		: T_FILETIME;
END_VAR
VAR
END_VAR
(*
-------------------------------------------------------------------------------------------------
Date		Version	Author	Comments
-------------------------------------------------------------------------------------------------
26/03/2012	1.38.00	PB		Initial release

-------------------------------------------------------------------------------------------------
*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[MEMMOVE(ADR(F_FILE_FileTimeToULarge), ADR(sFileTime), SIZEOF(F_FILE_FileTimeToULarge));]]></ST>
    </Implementation>
    <LineIds Name="F_FILE_FileTimeToULarge">
      <LineId Id="15" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>