<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="F_FileTimeToULarge" Id="{96e2b798-2701-475b-9c2d-58c3657e1a9c}" SpecialFunc="None">
    <Declaration><![CDATA[(* convert value from 64-bit T_FILETIME to 64-bit T_ULARGE_INTEGER *)
FUNCTION F_FileTimeToULarge : T_ULARGE_INTEGER
VAR_INPUT
	sFileTime		: T_FILETIME;
END_VAR
VAR
END_VAR
(*
-------------------------------------------------------------------------------------------------
Date		Version	Author	Comments
-------------------------------------------------------------------------------------------------
30/01/2015	3.00.00	PB		Moved from Sewtec_CaseTrace.lib

-------------------------------------------------------------------------------------------------
26/03/2012	1.38.00	PB		Initial release

-------------------------------------------------------------------------------------------------
*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[MEMMOVE(ADR(F_FileTimeToULarge), ADR(sFileTime), SIZEOF(F_FileTimeToULarge));]]></ST>
    </Implementation>
    <LineIds Name="F_FileTimeToULarge">
      <LineId Id="18" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>