<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="F_ULargeToFileTime" Id="{a27e91ec-2dce-4820-aca4-d5f526e03aa7}" SpecialFunc="None">
    <Declaration><![CDATA[(* convert value from 64-bit T_ULARGE_INTEGER to 64-bit T_FILETIME *)
FUNCTION F_ULargeToFileTime : T_FILETIME
VAR_INPUT
	nULarge			: T_ULARGE_INTEGER;
END_VAR
VAR
END_VAR
(*
-------------------------------------------------------------------------------------------------
Date		Version	Author	Comments
-------------------------------------------------------------------------------------------------
30/01/2015	3.00.00	PB		Moved from Sewtec_CaseTrace.lib

-------------------------------------------------------------------------------------------------
03/08/2012	1.39.00	PB		Initial release

-------------------------------------------------------------------------------------------------
*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[MEMMOVE(ADR(F_ULargeToFileTime), ADR(nULarge), SIZEOF(F_ULargeToFileTime));]]></ST>
    </Implementation>
    <LineIds Name="F_ULargeToFileTime">
      <LineId Id="18" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>