<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_IsNumber" Id="{be9138be-b37b-4501-8d6e-7e23f70be1bc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_IsNumber : BOOL
(*Returns true if the charachter is a number*)
VAR_INPUT
	sChr				: STRING(1);
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_IsNumber := (F_ToASC(sChr) >= 16#30 AND F_ToASC(sChr) <= 16#39);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>