<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="A05_StartupReportingDB" Id="{457e13fb-0733-456c-9d7b-38fdc7c4bc19}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM A05_StartupReportingDB
VAR
	
	ton_Watchdog: TON;
	nLastWatchdogFromReportingDB	: DINT;
	bWait: BOOL;
	
	rtStratupComplete 	: r_trig;
	nShiftID			: INT;
	
	nCameraIndex	: INT;
	
END_VAR
]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Fbd"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"A05_StartupReportingDB.Watchdog"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">21L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" />
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">false</v>
                      <v n="ENO">false</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">22L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">18L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"A05_StartupReportingDB.ReportingStatus"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">15L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" />
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">false</v>
                      <v n="ENO">false</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">16L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">5L</v>
                </o>
              </l2>
              <v n="BranchCounter">0</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
    <Action Name="ReportingStatus" Id="{51f01e5b-8cb0-417d-874a-12986c85fe46}">
      <Implementation>
        <ST><![CDATA[gDevice.stReportingDB.sPLCVersionHMI				:= gHMI.sPLCVersionHMI;
gDevice.stReportingDB.sPLCVersionInfoHMI			:= gHMI.sPLCVersionInfoHMI;

gDevice.stReportingDB.stMachineID.ProductionLine	:= gDevice.stMetsStatus.stPCMStatus.sProductionLine;
gDevice.stReportingDB.stMachineID.ProductionSite	:= gDevice.stMetsStatus.stPCMStatus.sProductionSite;

MEMMOVE(ADR(gDevice.stReportingDB.stMachineState), ADR(gDevice.stMachineState),SIZEOF(gDevice.stMachineState));

gDevice.stReportingDB.bMainItemReset				:= gDevice.stMetsStatus.bLongReset;

rtStratupComplete(CLK:= gDevice.stMetsStatus.bStartUpComplete);
IF rtStratupComplete.Q	THEN
	gDevice.stReportingDB.sStartDateTime			:= F_SYSTEM_SystemTimeAsISO8601(gDevice.stMetsStatus.stCTDateTime.sSystemTime, gDevice.stMetsStatus.stCTDateTime.sUTCTimeZoneOffset );
END_IF

nShiftID	:= gDevice.stReportingDB.nShiftID;				

gDevice.stReportingDB.nCodingAndTrackingMode		:= gDevice.stMetsStatus.stPCMStatus.nOpMode;
gDevice.stReportingDB.sBatchNumber					:= gDevice.stMetsStatus.stPCMStatus.sBatchNumber;
gDevice.stReportingDB.sProductionOrder				:= gDevice.stMetsStatus.stPCMStatus.sProductionOrder;
gDevice.stReportingDB.sRetailSKU 					:= gDevice.stMetsStatus.stPCMStatus.sRetailSKU;
gDevice.stReportingDB.sProductDescription			:= gDevice.stMetsStatus.stPCMStatus.sProductDescription;

(* Amount Of  Packs per Outer unit for current PCM *)
gDevice.stReportingDB.nPacksPerOuter				:= gDevice.stMetsStatus.stPCMStatus.nPacksPerOuter;	
(* Amount Of  Packs per Case unit for current PCM *)	
gDevice.stReportingDB.nPacksPerCase					:= gDevice.stMetsStatus.stPCMStatus.nPacksPerCase;		
(* Amount Of  Outers  per Case unit for current PCM *)	
gDevice.stReportingDB.nOutersPerCase				:= gDevice.stMetsStatus.stPCMStatus.nOutersPerCase;			

FOR nCameraIndex := 1 TO cMAX_CAMERA_NUMBER DO
	gDevice.stReportingDB.aCameraName[nCameraIndex] := gDevice.stMachineConfig.aCameraSettings[nCameraIndex].sDeviceName;
END_FOR
]]></ST>
      </Implementation>
    </Action>
    <Action Name="Watchdog" Id="{b16be1d6-0538-4d14-8f37-dbffcd90d179}">
      <Implementation>
        <ST><![CDATA[(*Watchdog to Bridge*)
gDevice.nWatchdogToReportingDB := gDevice.nWatchdogToReportingDB + 1;
IF  gDevice.nWatchdogToReportingDB > 10000 THEN
	gDevice.nWatchdogToReportingDB := 1;
END_IF

gDevice.nWatchdogFromReportingDB	:=	gDevice.stReportingDB.nReportingDBWatchdog;
(*Watchdog from HMI - check if running*)
IF ton_Watchdog.Q THEN
	bWait := FALSE;
	IF gDevice.nWatchdogFromReportingDB <> nLastWatchdogFromReportingDB THEN
		gDevice.stMetsStatus.bReportingDBRunning := TRUE;
		nLastWatchdogFromReportingDB := gDevice.nWatchdogFromReportingDB;
	ELSE
		gDevice.stMetsStatus.bReportingDBRunning := FALSE;
	END_IF
ELSE
	bWait := TRUE;
END_IF

ton_Watchdog(IN:= bWait, PT := t#4000ms);]]></ST>
      </Implementation>
    </Action>
  </POU>
</TcPlcObject>