<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_SafeTo_UDINT" Id="{e57ec556-65f3-432c-b1d6-e2eb11108bee}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_SafeTo_UDINT : UDINT
VAR_INPUT
	nCovertVar	: Dint;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_SafeTo_UDINT := TO_UDINT(MAX(0,nCovertVar));]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>