<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="C21_CamerasCtrl" Id="{2037e324-dea3-4f0c-806a-b675c4c0e95a}" SpecialFunc="None">
    <Declaration><![CDATA[ PROGRAM C21_CamerasCtrl
VAR
END_VAR]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Fbd"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"Camera01"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">5L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Program</v>
                      <n n="EN" />
                      <n n="ENO" />
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">6L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">4L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"Camera02"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">8L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Program</v>
                      <n n="EN" />
                      <n n="ENO" />
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">9L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">7L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"Camera03"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">11L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Program</v>
                      <n n="EN" />
                      <n n="ENO" />
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">12L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">10L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"Camera04"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">14L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Program</v>
                      <n n="EN" />
                      <n n="ENO" />
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">15L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">13L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"Camera05"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">17L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Program</v>
                      <n n="EN" />
                      <n n="ENO" />
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">18L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">16L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"Camera06"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">20L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Program</v>
                      <n n="EN" />
                      <n n="ENO" />
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">21L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">19L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"Camera07"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">23L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Program</v>
                      <n n="EN" />
                      <n n="ENO" />
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">24L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">22L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"Camera08"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">26L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Program</v>
                      <n n="EN" />
                      <n n="ENO" />
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">27L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">25L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"Camera09"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">29L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Program</v>
                      <n n="EN" />
                      <n n="ENO" />
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">30L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">28L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"Camera10"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">32L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Program</v>
                      <n n="EN" />
                      <n n="ENO" />
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">33L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">31L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"Camera11"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">35L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Program</v>
                      <n n="EN" />
                      <n n="ENO" />
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">36L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">34L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"Camera12"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">38L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Program</v>
                      <n n="EN" />
                      <n n="ENO" />
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">39L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">37L</v>
                </o>
              </l2>
              <v n="BranchCounter">1</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
    <Action Name="Camera01" Id="{d9410514-f5a0-4cd7-b192-96147cc84076}">
      <Implementation>
        <ST><![CDATA[(*********************************************************CAMERA 01**********************************************************************)

(*stMasterListCameraOptions		: ST_SCANNER_Options := (eScannerType := E_MV_420_FULL, nImageBuffer := 1, nExpectedResp := 1);*)
IF gProcess.ePackAggregationMode <> E_SYSTEM_PAOL_2CAM AND gProcess.ePackAggregationMode <> E_SYSTEM_PAOL_3CAM  THEN

	gDevice.aCameraLightingIntensity[1] := F_SCANNER_LightingIntensity(gDevice.stMachineConfig.aCameraSettings[1].nLightingIntensity);

	gDevice.aCameraControl[1].stOptions.bUseExternalLight := gDevice.stMachineConfig.aCameraSettings[1].bUseExternalLight;
	gDevice.aCameraControl[1].stOptions.eScannerType	:= gDevice.stMachineConfig.aCameraSettings[1].eScannerType;

	IF gDevice.aCameraControl[1].stOptions.eScannerType = E_SCANNER_DeviceType.V430F THEN

		gDevice.aCameraControl[1].stOptions.nImageBuffer	:= 1;
		gDevice.aCameraControl[1].stOptions.nExpectedResp := 1;
		gDevice.aCameraControl[1].nReqProgram := 1;

	ELSE

		gDevice.aCameraControl[1].stOptions.nImageBuffer 	:= gDevice.stMachineConfig.aCameraSettings[1].nImageBuffer;
		gDevice.aCameraControl[1].stOptions.nExpectedResp := gDevice.stMachineConfig.aCameraSettings[1].nExpectedResp;

		CASE gDevice.stMachineConfig.aCameraSettings[1].eExpectedType OF
				E_SCANNER_CodeType.DATAMARTIX:
					gDevice.aCameraControl[1].nReqProgram := 1;
				E_SCANNER_CodeType.DOTCODE:
					gDevice.aCameraControl[1].nReqProgram := 2;
				E_SCANNER_CodeType.QR:
					gDevice.aCameraControl[1].nReqProgram := 3;
				E_SCANNER_CodeType.CODE128:
					gDevice.aCameraControl[1].nReqProgram := 4;
			ELSE
				gDevice.aCameraControl[1].nReqProgram := 1;
			END_CASE
	END_IF
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="Camera02" Id="{fd089a61-2748-49c3-a78a-a8f7930551e9}">
      <Implementation>
        <ST><![CDATA[(*********************************************************CAMERA 02**********************************************************************)
(*stPackAggregationCameraOptions		: ST_SCANNER_Options := (eScannerType := E_MV_420_FULL, nImageBuffer := 1, nExpectedResp := 1);*)
(*stPackAggregationCameraOptions		: ST_SCANNER_Options := (eScannerType := E_MV_None, nImageBuffer := 1, nExpectedResp := 5);*)
(*stPackAggregationCameraOptions		: ST_SCANNER_Options := (eScannerType := E_MV_None, nImageBuffer := 1, nExpectedResp := 2);*)
IF gProcess.ePackAggregationMode <> E_SYSTEM_PAOL_2CAM AND gProcess.ePackAggregationMode <> E_SYSTEM_PAOL_3CAM  THEN

	gDevice.aCameraLightingIntensity[2] := F_SCANNER_LightingIntensity(gDevice.stMachineConfig.aCameraSettings[2].nLightingIntensity);

	gDevice.aCameraControl[2].stOptions.bUseExternalLight := gDevice.stMachineConfig.aCameraSettings[2].bUseExternalLight;
	gDevice.aCameraControl[2].stOptions.eScannerType	:= gDevice.stMachineConfig.aCameraSettings[2].eScannerType;

	IF gDevice.aCameraControl[2].stOptions.eScannerType = E_SCANNER_DeviceType.V430F THEN

		gDevice.aCameraControl[2].stOptions.nImageBuffer	:= 1;
		gDevice.aCameraControl[2].stOptions.nExpectedResp := 1;
		gDevice.aCameraControl[2].nReqProgram := 1;

	ELSE

		gDevice.aCameraControl[2].stOptions.nImageBuffer 	:= gDevice.stMachineConfig.aCameraSettings[2].nImageBuffer;
		gDevice.aCameraControl[2].stOptions.nExpectedResp := gDevice.stMachineConfig.aCameraSettings[2].nExpectedResp;

		CASE gDevice.stMachineConfig.aCameraSettings[2].eExpectedType OF
				E_SCANNER_CodeType.DATAMARTIX:
					gDevice.aCameraControl[2].nReqProgram := 1;
				E_SCANNER_CodeType.DOTCODE:
					gDevice.aCameraControl[2].nReqProgram := 2;
				E_SCANNER_CodeType.QR:
					gDevice.aCameraControl[2].nReqProgram := 3;
				E_SCANNER_CodeType.CODE128:
					gDevice.aCameraControl[2].nReqProgram := 4;
			ELSE
				gDevice.aCameraControl[2].nReqProgram := 1;
			END_CASE
	END_IF
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="Camera03" Id="{0c24c973-69ad-4e38-92d4-2e815ec5051a}">
      <Implementation>
        <ST><![CDATA[(*********************************************************CAMERA 03**********************************************************************)

(*stPackAggregationCameraOptions		: ST_SCANNER_Options := (eScannerType := E_MV_420_FULL, nImageBuffer := 1, nExpectedResp := 1);*)
(*stPackAggregationCameraOptions		: ST_SCANNER_Options := (eScannerType := E_MV_None, nImageBuffer := 1, nExpectedResp := 5);*)
(*stPackAggregationCameraOptions		: ST_SCANNER_Options := (eScannerType := E_MV_None, nImageBuffer := 1, nExpectedResp := 2);*)
IF gProcess.ePackAggregationMode <> E_SYSTEM_PAOL_2CAM AND gProcess.ePackAggregationMode <> E_SYSTEM_PAOL_3CAM  THEN

	gDevice.aCameraLightingIntensity[3] := F_SCANNER_LightingIntensity(gDevice.stMachineConfig.aCameraSettings[3].nLightingIntensity);

	gDevice.aCameraControl[3].stOptions.bUseExternalLight := gDevice.stMachineConfig.aCameraSettings[3].bUseExternalLight;
	gDevice.aCameraControl[3].stOptions.eScannerType	:= gDevice.stMachineConfig.aCameraSettings[3].eScannerType;

	IF gDevice.aCameraControl[3].stOptions.eScannerType = E_SCANNER_DeviceType.V430F THEN

		gDevice.aCameraControl[3].stOptions.nImageBuffer	:= 1;
		gDevice.aCameraControl[3].stOptions.nExpectedResp := 1;
		gDevice.aCameraControl[3].nReqProgram := 1;

	ELSE

		gDevice.aCameraControl[3].stOptions.nImageBuffer 	:= gDevice.stMachineConfig.aCameraSettings[3].nImageBuffer;
		gDevice.aCameraControl[3].stOptions.nExpectedResp := gDevice.stMachineConfig.aCameraSettings[3].nExpectedResp;

		CASE gDevice.stMachineConfig.aCameraSettings[3].eExpectedType OF
				E_SCANNER_CodeType.DATAMARTIX:
					gDevice.aCameraControl[3].nReqProgram := 1;
				E_SCANNER_CodeType.DOTCODE:
					gDevice.aCameraControl[3].nReqProgram := 2;
				E_SCANNER_CodeType.QR:
					gDevice.aCameraControl[3].nReqProgram := 3;
				E_SCANNER_CodeType.CODE128:
					gDevice.aCameraControl[3].nReqProgram := 4;
			ELSE
				gDevice.aCameraControl[3].nReqProgram := 1;
			END_CASE
	END_IF
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="Camera04" Id="{118670b7-c542-4a0f-bed4-00506a5fe966}">
      <Implementation>
        <ST><![CDATA[(*********************************************************CAMERA 04**********************************************************************)
gDevice.aCameraLightingIntensity[4] := F_SCANNER_LightingIntensity(gDevice.stMachineConfig.aCameraSettings[4].nLightingIntensity);

gDevice.aCameraControl[4].stOptions.bUseExternalLight := gDevice.stMachineConfig.aCameraSettings[4].bUseExternalLight;
gDevice.aCameraControl[4].stOptions.eScannerType	:= gDevice.stMachineConfig.aCameraSettings[4].eScannerType;

IF gDevice.aCameraControl[4].stOptions.eScannerType = E_SCANNER_DeviceType.V430F THEN

	gDevice.aCameraControl[4].stOptions.nImageBuffer	:= 1;
	gDevice.aCameraControl[4].stOptions.nExpectedResp := 1;
	gDevice.aCameraControl[4].nReqProgram := 1;

ELSE

	gDevice.aCameraControl[4].stOptions.nImageBuffer 	:= gDevice.stMachineConfig.aCameraSettings[4].nImageBuffer;
	gDevice.aCameraControl[4].stOptions.nExpectedResp := gDevice.stMachineConfig.aCameraSettings[4].nExpectedResp;

	CASE gDevice.stMachineConfig.aCameraSettings[4].eExpectedType OF
			E_SCANNER_CodeType.DATAMARTIX:
				gDevice.aCameraControl[4].nReqProgram := 1;
			E_SCANNER_CodeType.DOTCODE:
				gDevice.aCameraControl[4].nReqProgram := 2;
			E_SCANNER_CodeType.QR:
				gDevice.aCameraControl[4].nReqProgram := 3;
			E_SCANNER_CodeType.CODE128:
				gDevice.aCameraControl[4].nReqProgram := 4;
		ELSE
			gDevice.aCameraControl[4].nReqProgram := 1;
		END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="Camera05" Id="{10ef1c76-670b-44ec-b902-44a38a23e7c9}">
      <Implementation>
        <ST><![CDATA[(*********************************************************CAMERA 05**********************************************************************)
gDevice.aCameraLightingIntensity[5] := F_SCANNER_LightingIntensity(gDevice.stMachineConfig.aCameraSettings[5].nLightingIntensity);

gDevice.aCameraControl[5].stOptions.bUseExternalLight := gDevice.stMachineConfig.aCameraSettings[5].bUseExternalLight;
gDevice.aCameraControl[5].stOptions.eScannerType	:= gDevice.stMachineConfig.aCameraSettings[5].eScannerType;
gDevice.aCameraControl[5].stOptions.nImageBuffer 	:= gDevice.stMachineConfig.aCameraSettings[5].nImageBuffer;
gDevice.aCameraControl[5].stOptions.nExpectedResp := gDevice.stMachineConfig.aCameraSettings[5].nExpectedResp;

CASE gDevice.stMachineConfig.aCameraSettings[5].eExpectedType OF
	E_SCANNER_CodeType.DATAMARTIX:
		gDevice.aCameraControl[5].nReqProgram := 1;
	E_SCANNER_CodeType.DOTCODE:
		gDevice.aCameraControl[5].nReqProgram := 2;
	E_SCANNER_CodeType.QR:
		gDevice.aCameraControl[5].nReqProgram := 3;
	E_SCANNER_CodeType.CODE128:
		gDevice.aCameraControl[5].nReqProgram := 4;
ELSE
	gDevice.aCameraControl[5].nReqProgram := 1;
END_CASE]]></ST>
      </Implementation>
    </Action>
    <Action Name="Camera06" Id="{398d5066-34a1-413d-9ce8-a0e0bc0a9858}">
      <Implementation>
        <ST><![CDATA[(*********************************************************CAMERA 06**********************************************************************)
gDevice.aCameraLightingIntensity[6] := F_SCANNER_LightingIntensity(gDevice.stMachineConfig.aCameraSettings[6].nLightingIntensity);

gDevice.aCameraControl[6].stOptions.bUseExternalLight := gDevice.stMachineConfig.aCameraSettings[6].bUseExternalLight;
gDevice.aCameraControl[6].stOptions.eScannerType	:= gDevice.stMachineConfig.aCameraSettings[6].eScannerType;
gDevice.aCameraControl[6].stOptions.nImageBuffer 	:= gDevice.stMachineConfig.aCameraSettings[6].nImageBuffer;
gDevice.aCameraControl[6].stOptions.nExpectedResp := gDevice.stMachineConfig.aCameraSettings[6].nExpectedResp;

CASE gDevice.stMachineConfig.aCameraSettings[6].eExpectedType OF
	E_SCANNER_CodeType.DATAMARTIX:
		gDevice.aCameraControl[6].nReqProgram := 1;
	E_SCANNER_CodeType.DOTCODE:
		gDevice.aCameraControl[6].nReqProgram := 2;
	E_SCANNER_CodeType.QR:
		gDevice.aCameraControl[6].nReqProgram := 3;
	E_SCANNER_CodeType.CODE128:
		gDevice.aCameraControl[6].nReqProgram := 4;
ELSE
	gDevice.aCameraControl[6].nReqProgram := 1;
END_CASE]]></ST>
      </Implementation>
    </Action>
    <Action Name="Camera07" Id="{56f527e9-b6be-4c6a-a391-2ba6e4e1fc6a}">
      <Implementation>
        <ST><![CDATA[(*********************************************************CAMERA 07**********************************************************************)
gDevice.aCameraLightingIntensity[7] := F_SCANNER_LightingIntensity(gDevice.stMachineConfig.aCameraSettings[7].nLightingIntensity);

gDevice.aCameraControl[7].stOptions.bUseExternalLight := gDevice.stMachineConfig.aCameraSettings[7].bUseExternalLight;
gDevice.aCameraControl[7].stOptions.eScannerType	:= gDevice.stMachineConfig.aCameraSettings[7].eScannerType;

IF gDevice.aCameraControl[7].stOptions.eScannerType = E_SCANNER_DeviceType.V430F THEN

	gDevice.aCameraControl[7].stOptions.nImageBuffer	:= 1;
	gDevice.aCameraControl[7].stOptions.nExpectedResp := 1;
	gDevice.aCameraControl[7].nReqProgram := 1;

ELSE

	gDevice.aCameraControl[7].stOptions.nImageBuffer 	:= gDevice.stMachineConfig.aCameraSettings[7].nImageBuffer;

	IF gDevice.stMachineConfig.bMasterListCameraDoubleRead AND NOT gDevice.stMachineConfig.bEANValidationEnable THEN
		gDevice.aCameraControl[7].stOptions.nExpectedResp := 2;
	ELSE
		gDevice.aCameraControl[7].stOptions.nExpectedResp := gDevice.stMachineConfig.aCameraSettings[7].nExpectedResp;
	END_IF

	CASE gDevice.stMachineConfig.aCameraSettings[7].eExpectedType OF
			E_SCANNER_CodeType.DATAMARTIX:
				gDevice.aCameraControl[7].nReqProgram := 1;
			E_SCANNER_CodeType.DOTCODE:
				gDevice.aCameraControl[7].nReqProgram := 2;
			E_SCANNER_CodeType.QR:
				gDevice.aCameraControl[7].nReqProgram := 3;
			E_SCANNER_CodeType.CODE128:
				gDevice.aCameraControl[7].nReqProgram := 4;
		ELSE
			gDevice.aCameraControl[7].nReqProgram := 1;
		END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="Camera08" Id="{0f55681b-10b9-4a23-baf9-625b1e8f9e5d}">
      <Implementation>
        <ST><![CDATA[(*********************************************************CAMERA 08**********************************************************************)
gDevice.aCameraLightingIntensity[8] := F_SCANNER_LightingIntensity(gDevice.stMachineConfig.aCameraSettings[8].nLightingIntensity);

gDevice.aCameraControl[8].stOptions.bUseExternalLight := gDevice.stMachineConfig.aCameraSettings[8].bUseExternalLight;
gDevice.aCameraControl[8].stOptions.eScannerType	:= gDevice.stMachineConfig.aCameraSettings[8].eScannerType;

IF gDevice.aCameraControl[8].stOptions.eScannerType = E_SCANNER_DeviceType.V430F THEN

	gDevice.aCameraControl[8].stOptions.nImageBuffer	:= 1;
	gDevice.aCameraControl[8].stOptions.nExpectedResp := 1;
	gDevice.aCameraControl[8].nReqProgram := 1;

ELSE

	gDevice.aCameraControl[8].stOptions.nImageBuffer 	:= gDevice.stMachineConfig.aCameraSettings[8].nImageBuffer;
	gDevice.aCameraControl[8].stOptions.nExpectedResp := gDevice.stMachineConfig.aCameraSettings[8].nExpectedResp;


	IF gDevice.aCameraControl[8].stOptions.nExpectedResp = 2 THEN

		CASE gDevice.stMachineConfig.aCameraSettings[8].eExpectedType OF
			E_SCANNER_CodeType.DATAMARTIX:
				gDevice.aCameraControl[8].nReqProgram := 2;
			E_SCANNER_CodeType.DOTCODE:
				gDevice.aCameraControl[8].nReqProgram := 4;
			E_SCANNER_CodeType.QR:
				gDevice.aCameraControl[8].nReqProgram := 6;
			E_SCANNER_CodeType.CODE128:
				gDevice.aCameraControl[8].nReqProgram := 8;
		ELSE
			gDevice.aCameraControl[8].nReqProgram := 2;
		END_CASE
	ELSE
		CASE gDevice.stMachineConfig.aCameraSettings[8].eExpectedType OF
			E_SCANNER_CodeType.DATAMARTIX:
				gDevice.aCameraControl[8].nReqProgram := 1;
			E_SCANNER_CodeType.DOTCODE:
				gDevice.aCameraControl[8].nReqProgram := 3;
			E_SCANNER_CodeType.QR:
				gDevice.aCameraControl[8].nReqProgram := 5;
			E_SCANNER_CodeType.CODE128:
				gDevice.aCameraControl[8].nReqProgram := 7;
		ELSE
			gDevice.aCameraControl[8].nReqProgram := 1;
		END_CASE
	END_IF

END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="Camera09" Id="{c7ae0c68-2f49-4b23-b98f-0d9ac65534a8}">
      <Implementation>
        <ST><![CDATA[(*********************************************************CAMERA 09**********************************************************************)
gDevice.aCameraLightingIntensity[9] := F_SCANNER_LightingIntensity(gDevice.stMachineConfig.aCameraSettings[9].nLightingIntensity);

gDevice.aCameraControl[9].stOptions.bUseExternalLight := gDevice.stMachineConfig.aCameraSettings[9].bUseExternalLight;
gDevice.aCameraControl[9].stOptions.eScannerType	:= gDevice.stMachineConfig.aCameraSettings[9].eScannerType;

IF gDevice.aCameraControl[9].stOptions.eScannerType = E_SCANNER_DeviceType.V430F THEN

	gDevice.aCameraControl[9].stOptions.nImageBuffer	:= 1;
	gDevice.aCameraControl[9].stOptions.nExpectedResp := 1;
	gDevice.aCameraControl[9].nReqProgram := 1;

ELSIF gDevice.stMachineConfig.bPassthrough AND gDevice.stMachineConfig.bEANValidationEnable THEN

	gDevice.aCameraControl[9].stOptions.nImageBuffer	:= 1;
	gDevice.aCameraControl[9].stOptions.nExpectedResp := 1;
	gDevice.aCameraControl[9].nReqProgram := 3;

ELSE

	gDevice.aCameraControl[9].stOptions.nImageBuffer 	:= gDevice.stMachineConfig.aCameraSettings[9].nImageBuffer;

	IF gDevice.stMachineConfig.bMasterListCameraDoubleRead  THEN

		gDevice.aCameraControl[9].stOptions.nExpectedResp := 2;
	ELSE
		gDevice.aCameraControl[9].stOptions.nExpectedResp := gDevice.stMachineConfig.aCameraSettings[9].nExpectedResp;
	END_IF

	IF gDevice.aCameraControl[9].stOptions.nExpectedResp = 2 THEN

		CASE gDevice.stMachineConfig.aCameraSettings[9].eExpectedType OF
			E_SCANNER_CodeType.DATAMARTIX:
				gDevice.aCameraControl[9].nReqProgram := 2;
			E_SCANNER_CodeType.DOTCODE:
				gDevice.aCameraControl[9].nReqProgram := 4;
			E_SCANNER_CodeType.QR:
				gDevice.aCameraControl[9].nReqProgram := 6;
			E_SCANNER_CodeType.CODE128:
				gDevice.aCameraControl[9].nReqProgram := 8;
		ELSE
			gDevice.aCameraControl[9].nReqProgram := 2;
		END_CASE
	ELSE
		CASE gDevice.stMachineConfig.aCameraSettings[9].eExpectedType OF
			E_SCANNER_CodeType.DATAMARTIX:
				gDevice.aCameraControl[9].nReqProgram := 1;
			E_SCANNER_CodeType.DOTCODE:
				gDevice.aCameraControl[9].nReqProgram := 3;
			E_SCANNER_CodeType.QR:
				gDevice.aCameraControl[9].nReqProgram := 5;
			E_SCANNER_CodeType.CODE128:
				gDevice.aCameraControl[9].nReqProgram := 7;
		ELSE
			gDevice.aCameraControl[9].nReqProgram := 1;
		END_CASE
	END_IF
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="Camera10" Id="{b3181e0d-72ba-46e6-8516-701bfaec35a0}">
      <Implementation>
        <ST><![CDATA[(*********************************************************CAMERA 10**********************************************************************)
gDevice.aCameraLightingIntensity[10] := F_SCANNER_LightingIntensity(gDevice.stMachineConfig.aCameraSettings[10].nLightingIntensity);

gDevice.aCameraControl[10].stOptions.bUseExternalLight := gDevice.stMachineConfig.aCameraSettings[10].bUseExternalLight;
gDevice.aCameraControl[10].stOptions.eScannerType	:= gDevice.stMachineConfig.aCameraSettings[10].eScannerType;

IF gDevice.aCameraControl[10].stOptions.eScannerType = E_SCANNER_DeviceType.V430F THEN

	gDevice.aCameraControl[10].stOptions.nImageBuffer	:= 1;
	gDevice.aCameraControl[10].stOptions.nExpectedResp := 1;
	gDevice.aCameraControl[10].nReqProgram := 1;

ELSE

	gDevice.aCameraControl[10].stOptions.nImageBuffer 	:= gDevice.stMachineConfig.aCameraSettings[10].nImageBuffer;
	gDevice.aCameraControl[10].stOptions.nExpectedResp := gDevice.stMachineConfig.aCameraSettings[10].nExpectedResp;

	CASE gDevice.stMachineConfig.aCameraSettings[10].eExpectedType OF
			E_SCANNER_CodeType.DATAMARTIX:
				gDevice.aCameraControl[10].nReqProgram := 1;
			E_SCANNER_CodeType.DOTCODE:
				gDevice.aCameraControl[10].nReqProgram := 2;
			E_SCANNER_CodeType.QR:
				gDevice.aCameraControl[10].nReqProgram := 3;
			E_SCANNER_CodeType.CODE128:
				gDevice.aCameraControl[10].nReqProgram := 4;
		ELSE
			gDevice.aCameraControl[10].nReqProgram := 1;
		END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="Camera11" Id="{0f8b38eb-1911-4d68-aabf-cc764ae63cbf}">
      <Implementation>
        <ST><![CDATA[(*********************************************************CAMERA 11**********************************************************************)
gDevice.aCameraLightingIntensity[11] := F_SCANNER_LightingIntensity(gDevice.stMachineConfig.aCameraSettings[11].nLightingIntensity);

gDevice.aCameraControl[11].stOptions.bUseExternalLight := gDevice.stMachineConfig.aCameraSettings[11].bUseExternalLight;
gDevice.aCameraControl[11].stOptions.eScannerType	:= gDevice.stMachineConfig.aCameraSettings[11].eScannerType;

IF gDevice.aCameraControl[11].stOptions.eScannerType = E_SCANNER_DeviceType.V430F THEN

	gDevice.aCameraControl[11].stOptions.nImageBuffer	:= 1;
	gDevice.aCameraControl[11].stOptions.nExpectedResp := 1;
	gDevice.aCameraControl[11].nReqProgram := 1;

ELSE

	gDevice.aCameraControl[11].stOptions.nImageBuffer 	:= gDevice.stMachineConfig.aCameraSettings[11].nImageBuffer;
	gDevice.aCameraControl[11].stOptions.nExpectedResp := gDevice.stMachineConfig.aCameraSettings[11].nExpectedResp;

	CASE gDevice.stMachineConfig.aCameraSettings[11].eExpectedType OF
			E_SCANNER_CodeType.DATAMARTIX:
				gDevice.aCameraControl[11].nReqProgram := 1;
			E_SCANNER_CodeType.DOTCODE:
				gDevice.aCameraControl[11].nReqProgram := 2;
			E_SCANNER_CodeType.QR:
				gDevice.aCameraControl[11].nReqProgram := 3;
			E_SCANNER_CodeType.CODE128:
				gDevice.aCameraControl[11].nReqProgram := 4;
		ELSE
			gDevice.aCameraControl[11].nReqProgram := 1;
		END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="Camera12" Id="{ecfccefb-3927-4f0c-9372-3a1ca5f9b0d8}">
      <Implementation>
        <ST><![CDATA[(*********************************************************CAMERA 12**********************************************************************)
gDevice.aCameraLightingIntensity[12] := F_SCANNER_LightingIntensity(gDevice.stMachineConfig.aCameraSettings[12].nLightingIntensity);

gDevice.aCameraControl[12].stOptions.bUseExternalLight := gDevice.stMachineConfig.aCameraSettings[12].bUseExternalLight;
gDevice.aCameraControl[12].stOptions.eScannerType	:= gDevice.stMachineConfig.aCameraSettings[12].eScannerType;

IF gDevice.aCameraControl[12].stOptions.eScannerType = E_SCANNER_DeviceType.V430F THEN

	gDevice.aCameraControl[12].stOptions.nImageBuffer	:= 1;
	gDevice.aCameraControl[12].stOptions.nExpectedResp := 1;
	gDevice.aCameraControl[12].nReqProgram := 1;

ELSIF gDevice.stMetsStatus.stPCMStatus.nOpMode < 7 THEN

	gDevice.aCameraControl[12].stOptions.nImageBuffer	:= 1;
	gDevice.aCameraControl[12].stOptions.nExpectedResp := 1;
	gDevice.aCameraControl[12].nReqProgram := 5;

ELSE

	gDevice.aCameraControl[12].stOptions.nImageBuffer 	:= gDevice.stMachineConfig.aCameraSettings[12].nImageBuffer;
	gDevice.aCameraControl[12].stOptions.nExpectedResp := gDevice.stMachineConfig.aCameraSettings[12].nExpectedResp;

	CASE gDevice.stMachineConfig.aCameraSettings[12].eExpectedType OF
			E_SCANNER_CodeType.DATAMARTIX:
				gDevice.aCameraControl[12].nReqProgram := 1;
			E_SCANNER_CodeType.DOTCODE:
				gDevice.aCameraControl[12].nReqProgram := 2;
			E_SCANNER_CodeType.QR:
				gDevice.aCameraControl[12].nReqProgram := 3;
			E_SCANNER_CodeType.CODE128:
				gDevice.aCameraControl[12].nReqProgram := 4;
		ELSE
			gDevice.aCameraControl[12].nReqProgram := 1;
		END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
  </POU>
</TcPlcObject>